version: "3.9"

services:
  db:
    image: postgres:15
    container_name: scango_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: scango_web
    command: gunicorn ScanGo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
  nginix:
    image: nginx:latest
    container_name: scango_nginix
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web  

volumes:
  postgres_data:
  static_volume:
  media_volume: