# Generated by Django 5.2.6 on 2025-10-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
